### ISSUE TITLE
New PR's Welcome 

### ISSUE THREAD

**Issue by adityanjr** [adityanjr/hacktoberfest-2020#2]

**Comment by sayaPintar** [comment]
what i do sir?

**Comment by adityanjr** [comment]
head over to README over this repo.  Contribute there

**Comment by wireshark10** [comment]
HI @adityanjr can I start contributing to this repo for Hacktoberfest2020 ?

**Comment by adityanjr** [comment]
@wireshark10 Yes, just add your name in Contributions.md if you are beginner. For more you can head over to DS-Algo repo.
